//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteForAltanEmuce.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Contactid { get; set; }
        public string Contactname { get; set; }
        public string Contactmail { get; set; }
        public string Contactphone { get; set; }
        public string Contactmessage { get; set; }
    }
}
