//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteForAltanEmuce.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Serviceid { get; set; }
        public string Servicetitle { get; set; }
        public string Servicesubtitle { get; set; }
        public string Servicetext { get; set; }
    }
}
